---
- hosts: all
  tasks: 
  
  - name: Deploy and run the portainer
    community.docker.docker_container:
      name: portainer
      ports:
        - "9000:9000"
        - "8000:8000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
        
